---
- name: apt install
  become: true
  apt:
    pkg:
      - awscli
      - cloud-init
  tags:
    - apt

- name: cloud-init setup
  become: true
  template:
    src: cloud-init/00_setup.cfg
    dest: /etc/cloud/cloud.cfg.d/99zzzuws_00_setup.cfg
    owner: root
    group: root
    mode: '0640'
  tags:
    - host
    - cloud
