---
apiVersion: v1
kind: Service
metadata:
  name: k8s
  namespace: mon
  labels:
    app.kubernetes.io/name: k8s
spec:
  ports:
  - port: 2800
    name: k8smon
  selector:
    app.kubernetes.io/name: k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s
  namespace: mon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:mon-${K8S_IMAGE}-${VERSION}
          imagePullPolicy: IfNotPresent
          name: k8s
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 3000
          ports:
            - containerPort: 2800
              name: k8smon
          env:
            - name: UWS_DEPLOY
              value: "${UWS_DEPLOY}"
            - name: USER
              value: "uwsrun"
            - name: HOME
              value: "/home/uwsrun"
          envFrom:
            - configMapRef:
                name: cluster-env
          workingDir: /home/uwsrun
          volumeMounts:
            - name: tmpdir
              mountPath: "/tmp"
            - name: kube-cache
              mountPath: "/home/uwsrun/.kube/cache"
            - name: aws-auth
              mountPath: "/home/uwsrun/.aws"
              readOnly: true
            - name: cluster-auth
              mountPath: "/home/uwsrun/.kube/eksctl/clusters"
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            #~ limits:
              #~ cpu: 100m
              #~ memory: 500Mi
          command:
            - /usr/local/bin/k8smon
          livenessProbe:
            httpGet:
              path: /_/healthz
              port: 2800
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
      volumes:
        - name: tmpdir
          emptyDir:
            sizeLimit: 3Gi
        - name: aws-auth
          secret:
            secretName: aws-auth
        - name: cluster-auth
          secret:
            secretName: cluster-auth
        - name: kube-cache
          emptyDir:
            sizeLimit: 3Gi
