---
apiVersion: v1
kind: Service
metadata:
  name: munin-web
  namespace: mon
  labels:
    app.kubernetes.io/name: munin-web
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app.kubernetes.io/name: munin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: munin
  namespace: mon
spec:
  serviceName: munin
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: munin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: munin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:munin-${VERSION}
          imagePullPolicy: IfNotPresent
          name: munin
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: db
              mountPath: "/var/lib/munin"
            - name: cache
              mountPath: "/var/cache/munin/www"
            - name: log
              mountPath: "/var/log/munin"
            - name: tmpdir
              mountPath: "/tmp"
            - name: rundir
              mountPath: "/run"
            - name: munin-confd
              mountPath: "/srv/etc/munin/munin-conf.d"
              readOnly: true
            - name: munin-crond
              mountPath: "/srv/etc/cron.d"
              readOnly: true
            - name: munin-deploy-confd
              mountPath: "/etc/uws/conf"
              readOnly: true
            - name: smtps-ca
              mountPath: "/srv/etc/ca"
              readOnly: true
            - name: munin-alert
              mountPath: "/var/opt/munin-alert"
          resources:
            requests:
              cpu: 100m
              memory: 700Mi
            limits:
              cpu: 100m
              memory: 700Mi
          readinessProbe:
            exec:
              command:
                - cat
                - /etc/munin/munin.conf
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 1
        - image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:munin-web-${VERSION}
          imagePullPolicy: IfNotPresent
          name: munin-web
          ports:
            - containerPort: 80
              name: web
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: db
              mountPath: "/var/lib/munin"
              readOnly: true
            - name: cache
              mountPath: "/var/cache/munin/www"
              readOnly: true
            - name: web-tmpdir
              mountPath: "/tmp"
            - name: web-rundir
              mountPath: "/run"
            - name: cgi-tmp
              mountPath: "/var/lib/munin/cgi-tmp"
            - name: web-lockdir
              mountPath: "/var/lock"
          resources:
            requests:
              cpu: 100m
              memory: 700Mi
            limits:
              cpu: 100m
              memory: 700Mi
          readinessProbe:
            exec:
              command:
                - cat
                - /etc/munin/apache24.conf
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 1
      volumes:
        - name: tmpdir
          emptyDir:
            sizeLimit: 3Gi
        - name: rundir
          emptyDir:
            sizeLimit: 1Gi
        - name: web-tmpdir
          emptyDir:
            sizeLimit: 3Gi
        - name: web-rundir
          emptyDir:
            sizeLimit: 1Gi
        - name: cgi-tmp
          emptyDir:
            sizeLimit: 1Gi
        - name: web-lockdir
          emptyDir:
            sizeLimit: 1Gi
        - name: munin-alert
          emptyDir:
            sizeLimit: 1Gi
        - name: munin-confd
          configMap:
            name: munin-confd
        - name: munin-crond
          secret:
            secretName: munin-crond
        - name: munin-deploy-confd
          secret:
            secretName: munin-deploy-confd
        - name: smtps-ca
          secret:
            secretName: smtps-ca
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        storageClassName: efs-mon-munin-db
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi
    - metadata:
        name: cache
      spec:
        storageClassName: efs-mon-munin-cache
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: log
      spec:
        storageClassName: efs-mon-munin-log
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
