---
apiVersion: v1
kind: Service
metadata:
  name: munin-web
spec:
  type: ExternalName
  externalName: munin-web.mon.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: k8smon
spec:
  type: ExternalName
  externalName: k8s.mon.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: nginx-metrics
      port: 10254
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
spec:
  type: ExternalName
  externalName: metrics.ingress-nginx.svc.cluster.local

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: uwspod-test
#spec:
#  type: ExternalName
#  externalName: podtest.uwspod.svc.cluster.local

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-gateway
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/issuer: acme-prod
    nginx.ingress.kubernetes.io/auth-tls-secret: default/uwsca-ops
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${CLUSTER_HOST}.uws.talkingpts.org
      secretName: cluster-certificate
  rules:
    - host: ${CLUSTER_HOST}.uws.talkingpts.org
      http:
        paths:
          - pathType: Prefix
            path: /(munin/.*)
            backend:
              service:
                name: munin-web
                port:
                  number: 80
          - pathType: Prefix
            path: /(munin-cgi/.*)
            backend:
              service:
                name: munin-web
                port:
                  number: 80
          - pathType: Prefix
            path: /k8smon/(.*)
            backend:
              service:
                name: k8smon
                port:
                  number: 2800
          - pathType: Prefix
            path: /nginx/(.*)
            backend:
              service:
                name: nginx-metrics
                port:
                  number: 10254
#          - pathType: Prefix
#            path: /podtest/(.*)
#            backend:
#              service:
#                name: uwspod-test
#                port:
#                  number: 8699
