---
uws_domain: uws.talkingpts.org

asbenv: "{{ lookup('env', 'ASBENV') }}"
uws_acme_account: "{{ asbenv }}.key"

aws_region: "{{ lookup('env', 'AWS_REGION') }}"
aws_zone: "{{ lookup('env', 'AWS_ZONE') }}"

ansible_user: admin
ansible_host: "{{ inventory_hostname }}.{{ uws_domain }}"

ansible_common_remote_group: admin

vm_tag_name: ""
vm_public_dns_name: ""
vm_public_name: ""

debian_release: bullseye

postconf_mailname: ""
postconf_smtps_server: no

uws_users_homedir: /srv/home

uws_authorized_key:
  - jrmstp

uwsca_smtps: smtps/230503
uwsca_smtps_client: 08082dca-8d77-5c81-9a44-94642089b3b1

uws_smtps: "ops.{{ uws_domain }}"
uws_smtps_port: 328

uwsops_ecr: 789470191893.dkr.ecr.sa-east-1.amazonaws.com/uwsops
