---
apiVersion: v1
kind: Service
metadata:
  name: munin-node
  namespace: mon
  labels:
    app.kubernetes.io/name: munin-node
spec:
  ports:
  - port: 4949
    name: node
  selector:
    app.kubernetes.io/name: munin-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: munin-node
  namespace: mon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: munin-node
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: munin-node
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:munin-node-${VERSION}
          imagePullPolicy: IfNotPresent
          name: munin-node
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 4949
              name: node
          env:
            - name: UWS_DEPLOY
              value: "${UWS_DEPLOY}"
            - name: UWS_CLUSTER
              value: "${UWS_CLUSTER}"
          volumeMounts:
            - name: tmpdir
              mountPath: "/tmp"
            - name: rundir
              mountPath: "/run"
            - name: node-setup
              mountPath: "/srv/etc/munin-node"
              readOnly: true
            - name: munin-plugins
              mountPath: "/srv/munin/plugins"
              readOnly: true
            - name: ops-ca
              mountPath: "/uws/etc/ca/ops"
              readOnly: true
            - name: ops-ca-client
              mountPath: "/uws/etc/ca/client"
              readOnly: true
            - name: munin-plugins-pycache
              mountPath: "/srv/munin/plugins/__pycache__"
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            #~ limits:
              #~ cpu: 100m
              #~ memory: 500Mi
          readinessProbe:
            exec:
              command:
                - cat
                - /etc/munin/munin-node.conf
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 1
      volumes:
        - name: tmpdir
          emptyDir: {}
        - name: rundir
          emptyDir: {}
        - name: node-setup
          configMap:
            name: node-setup
        - name: munin-plugins
          configMap:
            name: munin-plugins
        - name: ops-ca
          configMap:
            name: ops-ca
        - name: ops-ca-client
          configMap:
            name: ops-ca-client
        - name: munin-plugins-pycache
          emptyDir: {}
